@startuml
'https://plantuml.com/class-diagram

class Solution42{
    +main(String[] args)
}

class FileProcessor{
    +List<String> getInputFromFile()
    +List<String> processInformation(List<String> info)
    +void displayInformation(List<String> processedInfo)
}

class FileProcessorTest{
    void getInputFromFile()
    void processInformation()
}


Solution42 *-- FileProcessor
FileProcessor - FileProcessorTest
@enduml