@startuml
'https://plantuml.com/class-diagram

class Solution45{

    +main(String[] args);

}

class FileProcessor{

    List<String> words
    +int processFile()
    +void writeToFile(String fileName)



}

Solution45*--FileProcessor

@enduml